name: Trigger Jenkins Pipeline

on:
  workflow_dispatch:
    inputs:
      POD_NAME:
        description: 'Name of the pod to delete'
        required: true
      NAMESPACE:
        description: 'Namespace of the pod'
        required: true

jobs:
  trigger-jenkins:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Github_Action
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/your-jenkins-job-name/buildWithParameters" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
          --data "POD_NAME=${{ github.event.inputs.POD_NAME }}" \
          --data "NAMESPACE=${{ github.event.inputs.NAMESPACE }}"
