name: Trigger Jenkins Pipeline

on:
  workflow_dispatch:
    inputs:
      POD_NAME:
        description: 'Name of the pod to delete'
        required: true
      NAMESPACE:
        description: 'Namespace of the pod'
        required: true
      CONTAINER_NAME:
        description: 'Container name'
        required: true

jobs:
  trigger-jenkins:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@v0.0.4
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: 'Github_Action'
          parameters: |
            POD_NAME=${{ github.event.inputs.POD_NAME }}
            NAMESPACE=${{ github.event.inputs.NAMESPACE }}
            CONTAINER_NAME=${{ github.event.inputs.CONTAINER_NAME }}
