name: Trigger Jenkins Pipeline

on:
  repository_dispatch:
    types: [trigger-jenkins]

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read input data
        id: read_input
        run: |
          POD_NAME=${{ github.event.client_payload.pod_name }}
          NAMESPACE=${{ github.event.client_payload.namespace }}
          CONTAINER_NAME=${{ github.event.client_payload.container_name }}
          echo "::set-output name=pod_name::$POD_NAME"
          echo "::set-output name=namespace::$NAMESPACE"
          echo "::set-output name=container_name::$CONTAINER_NAME"

      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@v0.0.4
        with:
          url: 'http://your-jenkins-server:8080'
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: 'your-jenkins-job-name'
          parameters: |
            POD_NAME=${{ steps.read_input.outputs.pod_name }}
            NAMESPACE=${{ steps.read_input.outputs.namespace }}
            CONTAINER_NAME=${{ steps.read_input.outputs.container_name }}
